// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumidityChange();
void onLightChange();
void onSoilMoisture0Change();
void onSoilMoisture1Change();
void onSoilMoisture2Change();
void onSoilMoisture3Change();
void onTempChange();

float humidity;
float light;
float soilMoisture0;
float soilMoisture1;
float soilMoisture2;
float soilMoisture3;
CloudTemperatureSensor relitiveTemp;
CloudTemperatureSensor soilTempF;
CloudTemperature temp;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);
  ArduinoCloud.addProperty(soilMoisture0, READWRITE, ON_CHANGE, onSoilMoisture0Change);
  ArduinoCloud.addProperty(soilMoisture1, READWRITE, ON_CHANGE, onSoilMoisture1Change);
  ArduinoCloud.addProperty(soilMoisture2, READWRITE, ON_CHANGE, onSoilMoisture2Change);
  ArduinoCloud.addProperty(soilMoisture3, READWRITE, ON_CHANGE, onSoilMoisture3Change);
  ArduinoCloud.addProperty(relitiveTemp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soilTempF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
